[package]
name = "ftx-otc-rs"
version = "0.1.0"
authors = ["Luiz Parreira <luizfilipester@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ftx_otc"

[dependencies]
serde_json = "1.0"
failure = "0.1"
hmac = "0.10"
sha2 = "0.9"
hex = "0.4"

[dependencies.reqwest]
version = "0.10"
features = ["json"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
